### PR TITLE
recipes-extended: add html2text

### PR DESCRIPTION
**Pull request by arthur-she**
Add html2text

Signed-off-by: Arthur <arthur.she@linaro.org>

### CODE REVIEW

**Comment by andrey-konovalov** [comment]
Where does this recipe come from? Maybe we could add the layer into the build instead of copying the recipe?

**Comment by arthur-she** [comment]
I created it. It will be used to dump igt-gpu-tools test result for debugging purpose. Please check this test job.
https://validation.linaro.org/scheduler/job/1915079#L2432

**Comment by andrey-konovalov** [comment]
Instead of html2text, did you try "lynx -dump" by a chance?

There is html2text package in debian - with quite some patches added, but the original source is fairly old (http://www.mbayer.de/html2text/downloads/html2text-1.3.2a.tar.gz is dated 22-May-2005) and doesn't seem to being updated any more.

The current recipe overrides do_configure and do_install. I would try to reuse autotools / autotools-brokensep better. I've tried that even, and it does require some more changes to Makefile.in.

**Comment by andrey-konovalov** [comment]
I've pushed my version of this recipe as a separate PR: https://github.com/linaro-mmwg/meta-lhg/pull/65

**Comment by andrey-konovalov** [comment]
The version of this change from https://github.com/linaro-mmwg/meta-lhg/pull/65 has been merged into meta-lhg,rocko

**Pull request closed without merging**
