### PR TITLE
Master

### PR DESCRIPTION
**Pull request by arthur-she**
For igt-gpu-tools.

### CODE REVIEW

**Comment by andrey-konovalov** [comment]
1. Why not to use a bbappend for the existing igt-gpu-tools_1.23.bb recipe in meta-intel? (meta-intel is included into the RPB builds)
2. What is the reason to create libxmlrpc recipe? meta-oe has http://cgit.openembedded.org/meta-openembedded/tree/meta-oe/recipes-devtools/xmlrpc-c/xmlrpc-c_1.51.03.bb already

Also
- "igt-gpu-tools:" is bad commit name;
- none of the commits has the "Signed-off-by" line;
- the patches added to SRC_URI are just plain diffs: no header (no origin or author in particular), no explanation on the purpose of the patch, no upstream status (is it taken from some project, submitted upstream, or needs not to be sent upstream as something specific to our particular setup).

**Comment by petegriffin** [comment]
@arthur-she see these guidelines https://wiki.yoctoproject.org/wiki/Best_Known_Methods_(BKMs)_for_Package_Updating#Patches for best OE practices on patch formatting.

**Comment by andrey-konovalov** [comment]
@arthur-she You have added one commit fixing the previous commits. Instead you should have done 'push -f' with the new version of the patchset. This way you would get rid of the (non-git) igt-gpu-tools.bb automatically (you've forgot to delete this file).

The new version should have 2 commits: one which adds the new igt-gpu-tools_git.bb recipe (with all the patches from its SRC_URI; the commit name could be "igt-gpu-tools: add the git version of the recipe", and the commit description could say what recipe it was based on, and list the changes vs the original recipe like "Remove X11 dependency" etc), and the other commit which adds the xmlrpc-c_1.51.03.bbappend (the commit name should be  something like "xmlrpc-c: <a short description of the change>")

Thanks!

**Comment by andrey-konovalov** [comment]
This has been merged with some edits (two commits squashed into one, missing Signed-off-by added)

**Pull request closed without merging**
